version: '3.6'
networks:
  default:
    driver: overlay
    attachable: true

services:
  integration:
    ports:
      - '8100:8080'
    environment:
      INTEGRATION_ENV-CODE: 'center'
    deploy:
      placement:
        constraints:
          - node.labels.dc == hetzner
      resources:
        limits:
          memory: 2000M
    labels:
      filebeat: "springboot"
    depends_on:
      - activemq

  integration-control-ui:
    ports:
      - '8101:8080'
    deploy:
      placement:
        constraints:
          - node.labels.dc == hetzner
    labels:
      filebeat: "springboot"

  monitoring-service:
    ports:
      - '8102:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    deploy:
      placement:
        constraints:
          - node.labels.dc == hetzner
    labels:
      filebeat: "springboot"
    depends_on:
      - db

  registry-service:
    ports:
      - '8104:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    deploy:
      placement:
        constraints:
          - node.labels.dc == hetzner
    labels:
      filebeat: "springboot"
    depends_on:
      - db

  security-admin-backend:
    ports:
      - '8103:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    deploy:
      resources:
        limits:
          memory: 1000M
      placement:
        constraints:
          - node.labels.type == hetzner
    depends_on:
      - db

  activemq:
    ports:
      - '8120:8161'
      - '8116:61616'
    image: 'webcenter/activemq:5.14.3'
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - 'activemq-data:/data/activemq'
      - 'activemq-log:/var/log/activemq'
    deploy:
      resources:
        limits:
          memory: 2000M

  db:
    ports:
      - '8132:5432'
    image: postgres:11
    command: postgres -c 'max_connections=250'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2000M
      placement:
        constraints:
          - node.labels.type == hetzner

volumes:
  postgres-data:
  activemq-data:
  activemq-log:
        
