_Платформа для обмена сообщениями или файлами между системами._

link:++https://ci.i-novus.ru/view/platform/job/integration-bus.master.build/++[integration-bus.master.build]

`+jar необходимо запускать с командой:
-Dapp.home="/opt/integration/"
в эту директорию необходимо положить файл с properties и keystore'+`

=== Модули
*integration:*

* для работы модуля необходимо указать настройки в файле `+placeholders.properties+`

[source,java]
----
integration.registry.url='http://localhost:8099/registry'
integration.fileStoragePath='путь для папки входящих файлов'
integration.amqBroker.url='failover://tcp://localhost:61617'
integration.monitoring.url='http://localhost:8099/monitoring'
integration.audit.rest.url='http://docker.one:8816/api'
integration.envCode='код окружения'
integration.centralAdapter.url='url центрального сегмента (http://localhost:8080/ws/internal)'
integration.internalWsTimeout='таймаут отправки файлов (300000L)'
----
* файл `+placeholders.properties+` необходимо поместить в
classpath приложения

*registry-backend:*

* для работы модуля необходимо указать настройки в файле `+placeholders.properties+`

[source,java]
----
datasource.url='jdbc:postgresql://localhost:5433/integration'
datasource.username='user'
datasource.password='password'
----
* файл `+placeholders.properties+` необходимо поместить в
classpath приложения

* создать db и указать параметры в properties

*monitoring-backend:*

* для работы модуля необходимо указать настройки:

[source,java]
----
datasource.url='jdbc:postgresql://localhost:5433/integration'
datasource.username='user'
datasource.password='password'
----

* создать db и указать параметры в properties

*integration-control-ui:*

* war файл для запуска в tomcat


----
создать db (общая с registry-backend) и в Tomcat создать ресурс jdbc/integration
----




