_Платформа для обмена сообщениями или файлами между системами._

link:++https://ci.i-novus.ru/view/platform/job/integration-bus.master.build/++[integration-bus.master.build]

`+jar необходимо запускать с командой:
-Dapp.home="/opt/integration/"
в эту директорию необходимо положить файл с properties и keystore'+`

=== Модули
*integration:*

* для работы модуля необходимо указать настройки в файле `+placeholders.properties+`

[source,java]
----
registry.address='http://localhost:8099/registry'
sign.soap.key.store.password='пароль для keystore'
sign.soap.key.store.region.alias.name='alias ключа ситемы'
sign.soap.key.store.region.alias.password='пароль для alias'
file.storage.temp.path='путь для папки входящих файлов'
amq.broker.url='failover://tcp://localhost:61617'
monitoring.address='http://localhost:8099/monitoring'
env.code='код окружения'
----
* файл `+placeholders.properties+` необходимо поместить в
classpath приложения вместе с `+keystore (алгоритм RSA (SHA-256 with RSA))+`

*registry-backend:*

* для работы модуля необходимо указать настройки в файле `+placeholders.properties+`

[source,java]
----
datasource.url='jdbc:postgresql://localhost:5433/integration'
datasource.username='user'
datasource.password='password'
----
* файл `+placeholders.properties+` необходимо поместить в
classpath приложения

* создать db и указать параметры в properties

*monitoring-backend:*

* для работы модуля необходимо указать настройки:

[source,java]
----
datasource.url='jdbc:postgresql://localhost:5433/integration'
datasource.username='user'
datasource.password='password'
----

* создать db и указать параметры в properties

*integration-control-ui:*

* war файл для запуска в tomcat


----
создать db (общая с registry-backend) и в Tomcat создать ресурс jdbc/integration
----




