_Платформа для обмена сообщениями или файлами между системами._

link:++https://ci.i-novus.ru/view/platform/job/integration-bus.master.build/++[integration-bus.master.build]

`+jar необходимо запускать с командой:
-Dapp.home="/opt/integration/" --spring.cloud.bootstrap.location=/opt/integration/bootstrap.properties
В директорию /opt/integration/ необходимо положить файлы: bootstrap.properties, placeholders.properties и keystore'+`

* Пример `+bootstrap.properties+`:
[source,java]
----
spring.cloud.consul.config.prefix=integration #префикс пути настроек в consul
----
Для отключения настроек из consul, добавить `+spring.cloud.consul.config.enabled=false+`


=== Модули
*integration:*

* для работы модуля необходимо указать настройки в файле `+placeholders.properties+`

[source,java]
----
integration.registry.url='http://localhost:8099/registry'
integration.file-storage-path='путь для папки входящих файлов'
integration.activemq.broker-url='failover://tcp://localhost:61617'
integration.monitoring.url='http://localhost:8099/monitoring'
audit.rest.url='http://docker.one:8816/api'
integration.env-code='код окружения'
integration.central-adapter-url='url центрального сегмента (http://localhost:8080/ws/internal)'
integration.internal-ws-timeout='таймаут отправки файлов (300000L)'
----
* файл `+placeholders.properties+` необходимо поместить в
classpath приложения

*registry-backend:*

* для работы модуля необходимо указать настройки в файле `+placeholders.properties+`

[source,java]
----
datasource.url='jdbc:postgresql://localhost:5433/integration'
datasource.username='user'
datasource.password='password'
----
* файл `+placeholders.properties+` необходимо поместить в
classpath приложения

* создать db и указать параметры в properties

*monitoring-backend:*

* для работы модуля необходимо указать настройки:

[source,java]
----
datasource.url='jdbc:postgresql://localhost:5433/integration'
datasource.username='user'
datasource.password='password'
----

* создать db и указать параметры в properties

*integration-control-ui:*

* war файл для запуска в tomcat


----
создать db (общая с registry-backend) и в Tomcat создать ресурс jdbc/integration
----




