version: '3.6'
networks:
  default:
    driver: overlay
    attachable: true

services:
  integration:
    ports:
      - '8100:8080'
    environment:
      INTEGRATION_ENV-CODE: 'center'
      SPRING_CLOUD_CONSUL_CONFIG_PREFIX: integration-center
    deploy:
      resources:
        limits:
          memory: 2000M
      placement:
        constraints:
          - node.role == worker
    labels:
      filebeat: "springboot"
    depends_on:
      - activemq
    volumes:
      - 'integration-shared-data:/share/esb/output'

  integration-control-ui:
    ports:
      - '8101:8080'
    environment:
      SPRING_CLOUD_CONSUL_CONFIG_PREFIX: integration-ui-center
    deploy:
      placement:
        constraints:
          - node.role == worker
    labels:
      filebeat: "springboot"

  monitoring-service:
    ports:
      - '8102:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.30.1.29:5432/integration
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SPRING_DATASOURCE_USERNAME: integration
      SPRING_DATASOURCE_PASSWORD: integration
    deploy:
      placement:
        constraints:
          - node.role == worker
    labels:
      filebeat: "springboot"
    depends_on:
      - db

  registry-service:
    ports:
      - '8104:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.30.1.29:5432/integration
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SPRING_DATASOURCE_USERNAME: integration
      SPRING_DATASOURCE_PASSWORD: integration
    deploy:
      placement:
        constraints:
          - node.role == worker
    labels:
      filebeat: "springboot"
    depends_on:
      - db

  security-admin-backend:
    ports:
      - '8103:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.30.1.29:5432/integration
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SPRING_DATASOURCE_USERNAME: integration
      SPRING_DATASOURCE_PASSWORD: integration
    deploy:
      resources:
        limits:
          memory: 1000M
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - db

  activemq:
    ports:
      - '8105:8161'
      - '8106:61616'
    image: 'webcenter/activemq:5.14.3'
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - 'activemq-data:/data/activemq'
      - 'activemq-log:/var/log/activemq'
    deploy:
      resources:
        limits:
          memory: 2000M
      placement:
        constraints:
          - node.role == worker

  db:
    ports:
      - '8132:5432'
    image: postgres:11
    command: postgres -c 'max_connections=250'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2000M
      placement:
        constraints:
          - node.labels.type == db

  postgres:
    ports:
      - '8107:5432'
    image: 'postgres:11.8'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'keycloak'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2000M
      placement:
        constraints:
          - node.labels.type == db

  keycloak:
    ports:
      - '8108:8080'
    image: 'jboss/keycloak:9.0.3'
    environment:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'password'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_ADDR: 'postgres'
      DB_PORT: '5432'
    depends_on:
      - 'postgres'

volumes:
  activemq-data:
  activemq-log:
  postgres-data:
  integration-shared-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/share/erz/center/data
