version: "3.6"

services:

  integration:
    image: "${DOCKER_REGISTRY}/is/integration:${TAG}"

  integration-control-ui:
    image: "${DOCKER_REGISTRY}/is/integration-control-ui:${TAG}"

  monitoring-service:
    image: "${DOCKER_REGISTRY}/is/monitoring-service:${TAG}"

  registry-service:
    image: "${DOCKER_REGISTRY}/is/registry-service:${TAG}"

  security-admin-backend:
    image: "${DOCKER_REGISTRY}/is/security-admin-backend:${TAG}"

