version: '3.6'
networks:
  default:
    driver: overlay
    attachable: true

services:
  integration:
    ports:
      - '33450:8080'
    environment:
      INTEGRATION_ENV-CODE: 'center'
      SPRING_CLOUD_CONSUL_CONFIG_PREFIX: integration-center
    deploy:
      resources:
        limits:
          memory: 2000M
      placement:
        constraints:
          - node.role == worker
    labels:
      filebeat: "springboot"
    depends_on:
      - activemq
#    volumes:
#      - 'integration-shared-data:/share/esb/output'

  integration-control-ui:
    ports:
      - '33451:8080'
    environment:
      SPRING_CLOUD_CONSUL_CONFIG_PREFIX: integration-ui-center
    deploy:
      placement:
        constraints:
          - node.role == worker
    labels:
      filebeat: "springboot"

  monitoring-service:
    ports:
      - '33452:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/integration
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    deploy:
      placement:
        constraints:
          - node.role == worker
    labels:
      filebeat: "springboot"
    depends_on:
      - db

  registry-service:
    ports:
      - '33453:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/integration
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    deploy:
      placement:
        constraints:
          - node.role == worker
    labels:
      filebeat: "springboot"
    depends_on:
      - db

  security-admin-backend:
    ports:
      - '33454:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/integration
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    deploy:
      resources:
        limits:
          memory: 1000M
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - db

  activemq:
    ports:
      - '33455:8161'
      - '33456:61616'
    image: 'webcenter/activemq:5.14.3'
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - 'activemq-data:/data/activemq'
      - 'activemq-log:/var/log/activemq'
    deploy:
      resources:
        limits:
          memory: 2000M
      placement:
        constraints:
          - node.role == worker

  db:
    ports:
      - '33457:5432'
    image: postgres:11
    command: postgres -c 'max_connections=250'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'integration'
    volumes:
      - integration-bus-db-dev:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2000M

volumes:
  activemq-data:
  activemq-log:
  integration-bus-db-dev:
#  integration-shared-data:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: /opt/share/erz/center/data
