version: "3.6"

services:

  integration:
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/integration-bus/integration:${TAG}"

  integration-control-ui:
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/integration-bus/integration-control-ui:${TAG}"

  monitoring-service:
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/integration-bus/monitoring-service:${TAG}"

  registry-service:
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/integration-bus/registry-service:${TAG}"

  security-admin-backend:
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/integration-bus/security-admin-backend:${TAG}"

