version: '3.6'
networks:
  default:
    driver: overlay
    attachable: true

services:
  integration:
    ports:
      - '9100:8080'
    environment:
      INTEGRATION_ENV-CODE: 'region'
      SPRING_CLOUD_CONSUL_CONFIG_PREFIX: integration-region
      AUDIT_CLIENT_EBABLED: false
      AUDIT_SERVICE_URL: https://epmp.master.i-novus.ru/audit/service/api
    deploy:
      resources:
        limits:
          memory: 2000M
      placement:
        constraints:
          - node.role == worker
    labels:
      filebeat: "springboot"
    depends_on:
      - activemq
    volumes:
    - 'integration-shared-data:/share/esb/output'

  activemq:
    ports:
      - '9120:8161'
      - '9116:61616'
    image: 'webcenter/activemq:5.14.3'
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - 'activemq-data:/data/activemq'
      - 'activemq-log:/var/log/activemq'
    deploy:
      resources:
        limits:
          memory: 2000M
      placement:
        constraints:
          - node.role == worker

volumes:
  activemq-data:
  activemq-log:
  integration-shared-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/share/erz/center/data
        
