//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.15 at 03:22:22 PM MSK 
//


package ru.i_novus.integration.ws.internal;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for IntegrationMessage complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="IntegrationMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageData" type="{http://ws.integration.i_novus.ru/internal}MessageInfo" minOccurs="0"/>
 *         &lt;element name="Message" type="{http://ws.integration.i_novus.ru/internal}MessageData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "IntegrationMessage")
@XmlType(name = "IntegrationMessage", propOrder = {
        "messageData",
        "message"
})
public class IntegrationMessage {

    @XmlElement(name = "MessageData")
    protected MessageInfo messageData;
    @XmlElement(name = "Message")
    protected MessageData message;

    /**
     * Gets the value of the messageData property.
     *
     * @return possible object is
     * {@link MessageInfo }
     */
    public MessageInfo getMessageData() {
        return messageData;
    }

    /**
     * Sets the value of the messageData property.
     *
     * @param value allowed object is
     *              {@link MessageInfo }
     */
    public void setMessageData(MessageInfo value) {
        this.messageData = value;
    }

    /**
     * Gets the value of the message property.
     *
     * @return possible object is
     * {@link MessageData }
     */
    public MessageData getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     *
     * @param value allowed object is
     *              {@link MessageData }
     */
    public void setMessage(MessageData value) {
        this.message = value;
    }

}
